baseURL = 'https://blog.kousaka.co/'
languageCode = 'ja-jp'
title = 'ken.log'
theme = 'stack'
defaultContentLanguage = 'ja'
enableRobotsTXT = 'true'
hasCJKLanguage = 'true'
timeZone = 'Asia/Tokyo'

# URL Management
[permalinks]
post = '/:slug/'
page = '/p/:slug/'

# Markup
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

# settings for stack theme
[params.sidebar]
emoji = 'ğŸ™„'
subtitle = 'è¦šãˆã¦ãŠããŸã„ã“ã¨ã‚’ã€æ®‹ã—ã¦ãŠãã¨ã“ã‚ã€‚'
[params.sidebar.avatar]
src = 'img/avatar.webp'

[params.footer]
since = '2012'

# ç¾çŠ¶ãƒˆãƒƒãƒ—ç”»é¢å³ã®æ¤œç´¢ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã¯ä¸è¦ãªã®ã§ã‚³ãƒ¡ãƒ³ãƒˆã‚¢ã‚¦ãƒˆ
#[[params.widgets.homepage]]
#type = 'search'

[[params.widgets.page]]
type = 'toc'

[[menu.social]]
identifier = "mastodon-japan-net"
name = "Mastodon"
url = "https://mastodon-japan.net/@arkenous"

[menu.social.params]
icon = "mastodon"
